---
- name: Configure Projects and Policies
  hosts: bootstrap
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier

- name: Configure Operators for Istio, Elasticsearch, Jaeger, Kiali
  hosts: configure-operators
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier

- name: Configure the Service Mesh Control Plane
  hosts: istio-system
  tasks:
    - include_role:
        name: openshift-applier/roles/openshift-applier

