---
ansible_connection: local

build:
  NAME: '{{ app_name }}'

openshift_cluster_content:
  - object: app-builds
    content:
      - name: istio-operator
        template: '{{ playbook_dir }}/templates/istio-operator.yml'
        params: '{{ playbook_dir }}/params/istio-operator'
        namespace: istio-operator
        tags:
          - istio-operator

