---
ansible_connection: local

build:
  NAME: istio-operator

openshift_cluster_content:
  - object: app-builds
    content:
      - name: istio-operator
        template: '{{ playbook_dir }}/templates/istio-operator-auto.yml'
        params: '{{ playbook_dir }}/params/istio-operator'
        params_from_vars: "{{ istio_operator }}"
        namespace: "{{ istio_operator_namespace }}"
        tags:
          - istio-operator

