---
ansible_connection: local

build:
  NAME: '{{ app_name }}'

openshift_cluster_content:
  - object: app-builds
    content:
      - name: manager-360-fe-bc
        template: '{{ playbook_dir }}/templates/manager-360-fe-bc.yml'
        params: '{{ playbook_dir }}/params/manager-360-fe-bc'
        namespace: '{{ ci_cd_namespace }}'
        tags:
          - ci-cd
          - manager-front
      - name: manager-360-fe-build
        template: '{{ playbook_dir }}/templates/manager-360-fe-is.yml'
        params: '{{ playbook_dir }}/params/manager-360-fe-is'
        namespace: '{{ dev_namespace }}'
        tags:
          - build
          - manager-front
