---
ansible_connection: local

openshift_cluster_content:
  - object: app-builds
    content:
      - name: prereq-operator
        template: '{{ playbook_dir }}/templates/prereq-operator.yml'
        namespace: openshift-operators
