---
ansible_connection: local
# Create new projects with a given short name and display name
openshift_cluster_content:
- object: projectrequest
  content:
  - name: "{{ istio_operator_namespace }}"    
    template: "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/project-requests/create-project.yml"
    params_from_vars: "{{ istio_operator }}"
    action: create
    tags:
    - istio-operator
    - projects
- object: projectrequest
  content:
  - name: "{{ istio_system_namespace }}"  
    template: "{{ openshift_templates_raw }}/{{ openshift_templates_raw_version_tag }}/project-requests/create-project.yml"
    params_from_vars: "{{ istio_system }}"
    action: create
    tags:
    - istio-system
    - projects
