kind: Template
apiVersion: v1
metadata:
  name: istio-operator
  annotations:
    openshift.io/display-name: S2I App Build Template
    description: S2I binary build config to create an image with your app baked in.
    iconClass: fa-cube
    tags: s2i
objects:  
- apiVersion: maistra.io/v1
  kind: ServiceMeshMemberRoll
  metadata:
    name: default
  spec:
    members:
    # a list of projects joined into the service mesh
    - consultant-360-dev
    - appdev-demo
