kind: Template
apiVersion: v1
metadata:
  name: istio-member-roll
  annotations:
    openshift.io/display-name: Istio Member Roll
    description: Installing Istio Member Roll
    iconClass: fa-cube
    tags: istio
objects:  
- apiVersion: maistra.io/v1
  kind: ServiceMeshMemberRoll
  metadata:
    name: default
  spec:
    members:
    # a list of projects joined into the service mesh
    - appdev-demo #TODO: Make this configurable as well
