---
kind: Template
apiVersion: v1
metadata:
  name: '${NAME}'
  annotations:
    openshift.io/display-name: S2I App Build Template
    description: S2I binary build config to create an image with your app baked in.
    iconClass: fa-cube
    tags: s2i
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        build: '${NAME}'
      name: '${NAME}'
    spec: {}

  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: "${NAME}"
      name: "${NAME}"
    spec:
      selector:
        deploymentConfig: "${NAME}"
      ports: 
      - port: 8080
        targetPort: 8080
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: "${NAME}"
      name: "${NAME}"
    spec:
      host: ""
      to:
        name: "${NAME}"

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: "${NAME}"
      name: "${NAME}"
    spec:
      strategy: 
        type: Rolling
      replicas: 1
      selector:
        deploymentConfig: "${NAME}"
      template:
        metadata:
          labels:
            app: "${NAME}"
            deploymentConfig: "${NAME}"
          name: "${NAME}"
        spec: 
          containers:
          - name: "${NAME}"
            image: "${NAME}:latest"
            imagePullPolicy: Always
            ports: 
            - containerPort: 8080
              protocol: TCP
            env: 
            - name: POSTGRES_URI
              valueFrom:
                secretKeyRef:
                  name: postgresql-persistent-service-binding
                  key: uri
            - name: POSTGRES_DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-persistent-service-binding
                  key: database_name
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-persistent-service-binding
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-persistent-service-binding
                  key: password
      triggers:
      - type: ConfigChange
      - imageChangeParams:
          automatic: true
          containerNames:
          - "${NAME}"
          from:
            kind: ImageStreamTag
            name: "${NAME}:latest"
        type: ImageChange

parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all objects and the resulting imagestream.
    required: true
    value: s2i-app
labels:
  template: consultant-360-fe-build-template
