apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger
  namespace: openshift-operators 
spec:
  channel: alpha
  name: jaeger 
  source: redhat-operators
  sourceNamespace: openshift-marketplace