apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali
  namespace: openshift-operators
spec:
  installPlanApproval: Automatic
  name: kiali
  source: redhat-operators
  sourceNamespace: openshift-marketplace
