istio_operator_namespace: istio-operator
istio_system_namespace: istio-system

istio_system:
  NAMESPACE: 'istio-system'
  NAMESPACE_DISPLAY_NAME: 'istio-system'

openshift_templates_raw: "https://raw.githubusercontent.com/redhat-cop/openshift-templates"
openshift_templates_raw_version_tag: "v1.4.12"

istio_operator:
  NAMESPACE: "{{ istio_operator_namespace }}"
  NAMESPACE_DISPLAY_NAME: "{{ istio_operator_namespace }}"

istio_system:
  NAMESPACE: "{{ istio_system_namespace }}"
  NAMESPACE_DISPLAY_NAME: "{{ istio-system_namespace }}"